### ISSUE TITLE
Build a UI for add post/image screen using Flutter

### ISSUE THREAD

**Issue by roohaani786** [roohaani786/AIOChat#19]
**Build a UI screen for and add post screen with caption input image display and share buttons using white background and deep-purple icons and text.**

Make a new Flutter project named "issue19" and start working on it. After successfull completion, send @roohaani786  the repo on whatsapp.

Resources to look upon:-
1) https://www.youtube.com/watch?v=ergtH28giKE
2) https://www.youtube.com/watch?v=8-m_2UojKO0
3) https://flutter.dev/docs/development/ui/layout

For any help, ping up @roohaani786

**Comment by Shahanafatima1707** [comment]
Sent from Mail for Windows 10

From: Aman khan Roohaani
Sent: 09 September 2020 13:31
To: roohaani786/flashgram
Cc: SHAHANA FATIMA; Assign
Subject: [roohaani786/flashgram] Build a UI for add post/image screen usingFlutter (#19)

Build a UI screen for and add post screen with caption input image display and share buttons using white background and deep-purple icons and text.
Resources to look upon:-
1. https://www.youtube.com/watch?v=ergtH28giKE
2. https://www.youtube.com/watch?v=8-m_2UojKO0
3. https://flutter.dev/docs/development/ui/layout
For any help, ping up @roohaani786

**Comment by roohaani786** [comment]
Hainn @Shahanafatima1707 ??
