### ISSUE TITLE
Add full camera preview, flash widget and hold to shoot

### ISSUE THREAD

**Issue by roohaani786** [roohaani786/AIOChat#3]
Complete it by tonight

**Comment by shadaab88** [comment]
only hold and record video is reamain

**Comment by shadaab88** [comment]
and flash widget

**Comment by roohaani786** [comment]
https://stackoverflow.com/questions/52128572/flutter-execute-method-so-long-the-button-pressed

**Comment by roohaani786** [comment]
flash widget working partialiy
